name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_release:
    runs-on: ubuntu-latest
    name: Build openwrt-xray
    steps:
      - name: Show workflow information
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "VERSION=$(find ./ -type f -name "Makefile" | xargs grep "PKG_VERSION" "Makefile")" >> $GITHUB_ENV
          echo "::set-output name=ASSET_NAME::$_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
      - name: Build for x86_64
        env:
          WORKSPACE: ${{ github.workspace }}
        uses: woniuzfb/openwrt-xray/.github/targets/x86_64@v1
        with:
          compress-goproxy: 'n'
          exclude-assets: 'n'
          compress-upx: 'y'
          compatibility-mode: 'n'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.ipk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Done
        run: echo "Build complete - ${{ steps.last_build.outputs.date }}"
