name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_release:
    runs-on: ubuntu-20.04
    name: Build openwrt-xray
    steps:
      - name: Build for x86_64
        env:
          WORKSPACE: ${{ github.workspace }}
        uses: woniuzfb/openwrt-xray/.github/targets/x86_64@v1
        with:
          compress-goproxy: 'n'
          exclude-assets: 'n'
          compress-upx: 'y'
          compatibility-mode: 'n'
      - name: Copy Bin Files
        run: |
          find ./ -type f -name "*xray*.ipk" -exec cp {} "${{ github.workspace }}" \;
          find "${{ github.workspace }}" -type f -name "*.ipk" -exec ls -lh {} \;
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.ipk"
          tag: ${{ github.ref }}
          file_glob: true
      - name: Done
        run: echo "Build complete - ${{ steps.last_build.outputs.date }}"
