name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_release:
    runs-on: ubuntu-20.04
    name: Build openwrt-xray
    steps:
      - name: Build for x86_64
        env:
          WORKSPACE: ${{ github.workspace }}
        uses: woniuzfb/openwrt-xray/.github/targets/x86_64@v1
        id: last_build
        with:
          compress-goproxy: 'n'
          exclude-assets: 'n'
          compress-upx: 'y'
          compatibility-mode: 'n'
      - name: Generate release tag
        run: |
          touch release.txt
          echo "xray*" >> release.txt
      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v*.*.*
          body_path: release.txt
          files: '*.ipk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Done
        run: echo "Build complete - ${{ steps.last_build.outputs.date }}"
